# Generated by Django 4.1.5 on 2023-01-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
