# Generated by Django 4.1.5 on 2023-01-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='worker',
        ),
    ]
